[tool.poetry]
name = "upstream-config-util"
version = "1.1.1"
description = ""
authors = ["UpstreamData <brett@upstreamdata.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
PySimpleGUI = "^4.60.4"
matplotlib = "^3.6.2"
reportlab = "^3.6.12"
svglib = "^1.4.1"
pyasic = "^0.21"
pyperclip = "^1.8.2"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
cx-Freeze = "^6.13.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
