get_version_retries = 3
miner_get_data_retries = 3
ping_retries = 6
ping_timeout = 10 # Seconds
scan_threads = 300
config_threads = 300
reboot_threads = 300

logfile = false

### DEBUG MODE ###
# change this to debug = true
# to enable debug mode.
debug = false
# debug = true
