get_version_retries = 3
miner_get_data_retries = 3
ping_retries = 2
ping_timeout = 3 # Seconds
scan_threads = 300
config_threads = 300
reboot_threads = 300

logfile = false

speed_optimizations = true

### DEBUG MODE ###
# change this to debug = true
# to enable debug mode.
debug = false
# debug = true
